/** Rennen Plus case study: a representative set of the site's own isolated car
 *  thumbnails (from img.rennenplus.com.au/img/cars/thumbs, produced by Finbar
 *  for the build). Order matters: the grid shows the first 12 on a phone, 24 on
 *  a tablet, 32 on a laptop, 40 on a wide screen. */
export type RennenCar = { slug: string; label: string; src: string };

export const RENNEN_CARS: RennenCar[] = [
  { slug: "997-carrera", label: "Porsche 911 Carrera, 997.1", src: "/images/rennen-plus/cars/997-carrera.webp" },
  { slug: "992-gt3", label: "Porsche 911 GT3, 992", src: "/images/rennen-plus/cars/992-gt3.webp" },
  { slug: "porsche-930-turbo", label: "Porsche 911 Turbo, 930", src: "/images/rennen-plus/cars/porsche-930-turbo.webp" },
  { slug: "ferrari-488-pista", label: "Ferrari 488 Pista", src: "/images/rennen-plus/cars/ferrari-488-pista.webp" },
  { slug: "mclaren-720s", label: "McLaren 720S", src: "/images/rennen-plus/cars/mclaren-720s.webp" },
  { slug: "corvette-c8", label: "Corvette Stingray, C8", src: "/images/rennen-plus/cars/corvette-c8.webp" },
  { slug: "lamborghini-huracan", label: "Lamborghini Huracán", src: "/images/rennen-plus/cars/lamborghini-huracan.webp" },
  { slug: "bmw-m3-m4-g80", label: "BMW M3 / M4, G80", src: "/images/rennen-plus/cars/bmw-m3-m4-g80.webp" },
  { slug: "964-carrera", label: "Porsche 911 Carrera, 964", src: "/images/rennen-plus/cars/964-carrera.webp" },
  { slug: "718-gt4-rs", label: "Porsche 718 Cayman GT4 RS", src: "/images/rennen-plus/cars/718-gt4-rs.webp" },
  { slug: "cayenne-e3-s", label: "Porsche Cayenne S, E3", src: "/images/rennen-plus/cars/cayenne-e3-s.webp" },
  { slug: "aston-martin-v8-vantage", label: "Aston Martin V8 Vantage", src: "/images/rennen-plus/cars/aston-martin-v8-vantage.webp" },
  { slug: "993-turbo", label: "Porsche 911 Turbo, 993", src: "/images/rennen-plus/cars/993-turbo.webp" },
  { slug: "991-2-gt3", label: "Porsche 911 GT3, 991.2", src: "/images/rennen-plus/cars/991-2-gt3.webp" },
  { slug: "ferrari-812-superfast", label: "Ferrari 812 Superfast", src: "/images/rennen-plus/cars/ferrari-812-superfast.webp" },
  { slug: "audi-r8-typ4s", label: "Audi R8 V10, Typ 4S", src: "/images/rennen-plus/cars/audi-r8-typ4s.webp" },
  { slug: "macan-95b-2-s", label: "Porsche Macan S, 95B.2", src: "/images/rennen-plus/cars/macan-95b-2-s.webp" },
  { slug: "maserati-granturismo", label: "Maserati GranTurismo", src: "/images/rennen-plus/cars/maserati-granturismo.webp" },
  { slug: "lamborghini-urus", label: "Lamborghini Urus", src: "/images/rennen-plus/cars/lamborghini-urus.webp" },
  { slug: "986-boxster", label: "Porsche Boxster, 986", src: "/images/rennen-plus/cars/986-boxster.webp" },
  { slug: "992-2-turbo", label: "Porsche 911 Turbo S, 992.2", src: "/images/rennen-plus/cars/992-2-turbo.webp" },
  { slug: "alfa-giulia-quadrifoglio", label: "Alfa Romeo Giulia Quadrifoglio", src: "/images/rennen-plus/cars/alfa-giulia-quadrifoglio.webp" },
  { slug: "bentley-continental-gt-w12", label: "Bentley Continental GT", src: "/images/rennen-plus/cars/bentley-continental-gt-w12.webp" },
  { slug: "mclaren-gt-gts", label: "McLaren GT", src: "/images/rennen-plus/cars/mclaren-gt-gts.webp" },
  { slug: "996-gt3", label: "Porsche 911 GT3, 996", src: "/images/rennen-plus/cars/996-gt3.webp" },
  { slug: "997-2-gt2-rs", label: "Porsche 911 GT2 RS, 997.2", src: "/images/rennen-plus/cars/997-2-gt2-rs.webp" },
  { slug: "ferrari-roma", label: "Ferrari Roma", src: "/images/rennen-plus/cars/ferrari-roma.webp" },
  { slug: "bmw-m340i-g20", label: "BMW M340i, G20", src: "/images/rennen-plus/cars/bmw-m340i-g20.webp" },
  { slug: "panamera-970", label: "Porsche Panamera, 970", src: "/images/rennen-plus/cars/panamera-970.webp" },
  { slug: "987-cayman", label: "Porsche Cayman, 987.1", src: "/images/rennen-plus/cars/987-cayman.webp" },
  { slug: "lamborghini-gallardo", label: "Lamborghini Gallardo", src: "/images/rennen-plus/cars/lamborghini-gallardo.webp" },
  { slug: "corvette-c8-z06", label: "Corvette Z06, C8", src: "/images/rennen-plus/cars/corvette-c8-z06.webp" },
  { slug: "991-turbo", label: "Porsche 911 Turbo, 991.1", src: "/images/rennen-plus/cars/991-turbo.webp" },
  { slug: "ferrari-f355", label: "Ferrari F355", src: "/images/rennen-plus/cars/ferrari-f355.webp" },
  { slug: "cayenne-955-turbo", label: "Porsche Cayenne Turbo, 955", src: "/images/rennen-plus/cars/cayenne-955-turbo.webp" },
  { slug: "mclaren-mp4-12c", label: "McLaren MP4-12C", src: "/images/rennen-plus/cars/mclaren-mp4-12c.webp" },
  { slug: "maserati-quattroporte", label: "Maserati Quattroporte", src: "/images/rennen-plus/cars/maserati-quattroporte.webp" },
  { slug: "aston-martin-dbs", label: "Aston Martin DBS", src: "/images/rennen-plus/cars/aston-martin-dbs.webp" },
  { slug: "718-cayman", label: "Porsche 718 Cayman", src: "/images/rennen-plus/cars/718-cayman.webp" },
  { slug: "992-carrera", label: "Porsche 911 Carrera, 992.1", src: "/images/rennen-plus/cars/992-carrera.webp" },
];
