import Collage from "@/components/toombul/Collage";
import layout from "@/content/toombul-collage.json";
import layoutMobile from "@/content/toombul-collage-mobile.json";
import type { CollagePos } from "@/content/toombulCollage";

// Hero collage: the crest + bitmapped cricket paraphernalia, every item
// Floyd-Steinberg dithered and gradient-mapped to the crest's red -> yellow.
// Desktop positions come from toombul-collage.json (arranged with the
// in-page editor at /toombul?edit=1); phones use the portrait arrangement
// in toombul-collage-mobile.json (generated by scratchpad gen_mobile.py).
export default function Hero() {
  return <Collage layout={layout as CollagePos[]} layoutMobile={layoutMobile as CollagePos[]} />;
}
